<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>IGBZ.Domain.Tests</RootNamespace>
    <AssemblyName>IGBZ.Domain.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(MicrosoftTestSdkVersion)" />
    <PackageReference Include="xunit" Version="$(XunitVersion)" />
    <PackageReference Include="xunit.runner.visualstudio" Version="$(XunitRunnerVersion)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\IGBZ.Domain\IGBZ.Domain.csproj" />
  </ItemGroup>
</Project>
