<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>IGBZ.Api</RootNamespace>
    <AssemblyName>IGBZ.Api</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IGBZ.Domain\IGBZ.Domain.csproj" />
    <ProjectReference Include="..\IGBZ.Application\IGBZ.Application.csproj" />
    <ProjectReference Include="..\IGBZ.Infrastructure\IGBZ.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <!-- احراز هویت JWT برای Web API -->
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
  </ItemGroup>
</Project>
